### ISSUE TITLE
SyntaxError: unexpected token

### ISSUE THREAD

**Issue by d4vzz** [Kumar-Saksham/CSMM-CLI#1]
hey, i'm trying config/install items but every command result in this error (changing numbers or diretory, depending of command):
```
$ csmm config
   /usr/local/lib/node_modules/csmm-cli/src/commands/config.js:70
      } catch {
                  ^
   SyntaxError: Unexpected token {
   at fetch (/usr/local/lib/node_modules/csmm-cli/node_modules/@oclif/config/lib/plugin.js:170:21)
```
I used the gnome terminal, is this the problem?
it's like finding errors (_}_) in the scripts, but I don't understand js, so...

**Comment by Kumar-Saksham** [comment]
hmm, that seems like your node version doesn't support optional catch binding (using catch blocks without arguments) it should work for node version 10.3 and above. You can try updating your nodejs to something >=10.3.

**Comment by d4vzz** [comment]
after some problems with repositories, I did it! thanks, the update allowed :)
